plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - DataCollection.md
  - PythonSetup.md
  - IBLdata.md
  - Supervision.md
  - Writing.md
theme: jekyll-theme-minimal
