plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - vision_values.md
  - getting_started
  - mentoring.md
  - lab.md
  - inlab_experiments.md
  - online_experiments.md
  - tips.md
theme: jekyll-theme-minimal
